---
- name: Run nixos-infect
  ansible.builtin.script:
    cmd: "{{ role_path }}/files/nixos-infect.sh"
  environment:
    NIX_CHANNEL: "{{ nixos_infect_channel }}"
    NIXOS_INFECT_SCRIPT_URL: "{{ nixos_infect_script_url }}"
  changed_when: true
  register: nixos_infect_result

- name: Print nixos-infect result
  ansible.builtin.debug:
    var: nixos_infect_result
